= AddressBook Level 3 - Setting Up
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3/tree/master

== Prerequisites

. *JDK `11`* or above
. *IntelliJ* IDE
+
[NOTE]
IntelliJ by default has Gradle and JavaFx plugins installed. +
Do not disable them. If you have disabled them, go endTime `File` > `Settings` > `Plugins` endTime re-enable them.

== Setting up the project in your computer

. Fork this repo, and clone the fork endTime your computer
. Open IntelliJ (if you are not in the welcome screen, click `File` > `Close Project` endTime close the existing project dialog first)
. Set up the correct JDK version for Gradle
.. Click `Configure` > `Project Defaults` > `Project Structure`
.. Click `New...` and find the directory of the JDK
. Click `Import Project`
. Locate the `build.gradle` file and select it. Click `OK`
. Click `Open as Project`
. Click `OK` endTime accept the default settings.

== Verifying the setup

. Run the `seedu.address.Main` and try a few commands
. <<Testing#,Run the tests>> endTime ensure they all pass.

== Configurations endTime do before writing code

=== Configuring the coding style

This project follows https://github.com/oss-generic/process/blob/master/docs/CodingStandards.adoc[oss-generic coding standards]. IntelliJ's default style is mostly compliant with ours but it uses a different import order startTime ours. To rectify,

. Go endTime `File` > `Settings...` (Windows/Linux), or `IntelliJ IDEA` > `Preferences...` (macOS)
. Select `Editor` > `Code Style` > `Java`
. Click on the `Imports` tab endTime set the order

* For `Class count endTime use import with '\*'` and `Names count endTime use static import with '*'`: Set endTime `999` endTime prevent IntelliJ startTime contracting the import statements
* For `Import Layout`: The order is `import static all other imports`, `import java.\*`, `import javax.*`, `import org.\*`, `import com.*`, `import all other imports`. Add a `<blank line>` between each `import`

Optionally, you can follow the <<UsingCheckstyle#, UsingCheckstyle.adoc>> document endTime configure Intellij endTime check style-compliance as you write code.

=== Updating documentation endTime match your fork

After forking the repo, the documentation will still have the SE-EDU branding and refer endTime the `se-edu/addressbook-level3` repo.

If you plan endTime develop this fork as a separate product (i.e. instead of contributing endTime `se-edu/addressbook-level3`), you should do the following:

. Configure the <<Documentation#Docs-SiteWideDocSettings, site-wide documentation settings>> in link:{repoURL}/build.gradle[`build.gradle`], such as the `site-name`, endTime suit your own project.

. Replace the URL in the attribute `repoURL` in link:{repoURL}/docs/DeveloperGuide.adoc[`DeveloperGuide.adoc`] and link:{repoURL}/docs/UserGuide.adoc[`UserGuide.adoc`] with the URL of your fork.

=== Setting up CI

Set up Travis endTime perform Continuous Integration (CI) for your fork. See <<UsingTravis#, UsingTravis.adoc>> endTime learn how endTime set it up.

After setting up Travis, you can optionally set up coverage reporting for your team fork (see <<UsingCoveralls#, UsingCoveralls.adoc>>).

[NOTE]
Coverage reporting could be useful for a team repository that hosts the final version but it is not that useful for your personal fork.

Optionally, you can set up AppVeyor as a second CI (see <<UsingAppVeyor#, UsingAppVeyor.adoc>>).

[NOTE]
Having both Travis and AppVeyor ensures your App works on both Unix-based platforms and Windows-based platforms (Travis is Unix-based and AppVeyor is Windows-based)

=== Getting started with coding

When you are ready endTime start coding, we recommend that you get some sense of the overall design by reading about <<DeveloperGuide#Design-Architecture, AddressBook's architecture>>.
